### ISSUE TITLE
Pull down to refresh animation should use custom animation not default Android animation.

### ISSUE THREAD

**Issue by kvnloo** [HackIllinois/android-2017#88]
[Here's](https://github.com/HackIllinois/iOS/blob/master/HackIllinois/Animations/Refresh/refresh.json) a link to the json file for lottie from ios

**Comment by kevinhinterlong** [comment]
We'll have to add a library to use the custom view because of [this](https://stackoverflow.com/questions/33160585/make-a-custom-swiperefreshlayout-indicator)

Here are some libraries that can probably do it
- [android-Ultra-Pull-To-Refresh](https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh)
- [SmartRefreshLayout](https://github.com/scwang90/SmartRefreshLayout)
- [RecyclerRefreshLayou](https://github.com/dinuscxj/RecyclerRefreshLayout)
